export {default as PublicLayout} from './PublicLayout'
export {default as Homepage} from './Homepage'
export {default as News} from './News'
export {default as RentProperties} from './RentProperties'
export {default as SoldProperties} from './SoldProperties'